name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK + Build-Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip openjdk-17-jdk git

        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform

        # Install Android SDK Command-line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/

        # Accept licenses
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Fix sdkmanager path for Buildozer
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
              $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Build APK with Buildozer
      run: |
        buildozer android release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: bin/*.apk
