name: Build NeuroQuantumAI_App APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYALIAS_PASSWORD: ${{ secrets.KEYALIAS_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev python3-dev \
            libsqlite3-dev libjpeg-dev libpng-dev libfreetype6-dev libgl1-mesa-dev \
            libgles2-mesa-dev libgstreamer1.0 libgstreamer-plugins-base1.0 \
            openjdk-17-jdk unzip zip git

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: NeuroQuantumAI_App-release
          path: bin/*.apk
