name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.home }}/.buildozer/android/platform/android-sdk
      ANDROID_NDK_HOME: ${{ runner.home }}/.buildozer/android/platform/android-sdk/ndk/25.2.9519653
      PATH: ${{ runner.home }}/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:${{ runner.home }}/.buildozer/android/platform/android-sdk/platform-tools:${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libc6-dev \
            git zip unzip openjdk-17-jdk \
            python3-dev python3-pip python3-setuptools \
            libffi-dev libssl-dev libsqlite3-dev \
            zlib1g-dev libjpeg-dev libfreetype6-dev \
            autoconf automake libtool pkg-config

      - name: Install Cython & Buildozer
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Download & extract Android cmdline-tools
        run: |
          SDK="$ANDROID_SDK_ROOT"
          mkdir -p "$SDK"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          mkdir cmdline_tmp
          unzip -q cmdline.zip -d cmdline_tmp
          rm cmdline.zip

          # Przenieś do cmdline-tools/latest
          mkdir -p "$SDK/cmdline-tools/latest"
          mv cmdline_tmp/cmdline-tools/* "$SDK/cmdline-tools/latest/"
          rm -rf cmdline_tmp

      - name: Install SDK platforms, build-tools & NDK 25b
        run: |
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

      - name: Symlink sdkmanager & avdmanager for Buildozer
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/tools/bin"
          cp "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/"* "$ANDROID_SDK_ROOT/tools/bin/"

      - name: Build debug APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeuroQuantumAI-debug
          path: bin/*.apk
