name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK: $HOME/.buildozer/android/platform/android-sdk
      ANDROIDNDK: $HOME/.buildozer/android/platform/android-sdk/ndk/25.2.9519653
      ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-sdk/ndk/25.2.9519653
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      P4A_USE_SYSTEM_LIBFFI: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libc6-dev \
            git zip unzip openjdk-17-jdk \
            python3-dev python3-pip python3-setuptools \
            libffi-dev libssl-dev libsqlite3-dev \
            zlib1g-dev libjpeg-dev libfreetype6-dev \
            autoconf automake libtool pkg-config

      - name: Install Cython & Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install cython buildozer

      - name: Download & prepare Android SDK & NDK 25b
        run: |
          SDK_ROOT="$ANDROIDSDK"
          mkdir -p "$SDK_ROOT"
          cd "$SDK_ROOT"

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline-tools
          rm cmdline.zip

          mv cmdline-tools cmdline-temp
          mkdir -p cmdline-tools/latest
          mv cmdline-temp/* cmdline-tools/latest/
          rm -rf cmdline-temp

          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root="$SDK_ROOT" \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

          mkdir -p "$SDK_ROOT/tools/bin"
          cp "$SDK_ROOT/cmdline-tools/latest/bin/"* "$SDK_ROOT/tools/bin/"

      - name: Build debug APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeuroQuantumAI-debug
          path: bin/*.apk
